# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 360
  strategy:
    maxParallel: 8
    matrix:
      linux_VTK_WITH_OSMESAFalsempimpichpython3.6.____cpython:
        CONFIG: linux_VTK_WITH_OSMESAFalsempimpichpython3.6.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESAFalsempimpichpython3.7.____cpython:
        CONFIG: linux_VTK_WITH_OSMESAFalsempimpichpython3.7.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESAFalsempimpichpython3.8.____cpython:
        CONFIG: linux_VTK_WITH_OSMESAFalsempimpichpython3.8.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESAFalsempinompipython3.6.____cpython:
        CONFIG: linux_VTK_WITH_OSMESAFalsempinompipython3.6.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESAFalsempinompipython3.7.____cpython:
        CONFIG: linux_VTK_WITH_OSMESAFalsempinompipython3.7.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESAFalsempinompipython3.8.____cpython:
        CONFIG: linux_VTK_WITH_OSMESAFalsempinompipython3.8.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESAFalsempiopenmpipython3.6.____cpython:
        CONFIG: linux_VTK_WITH_OSMESAFalsempiopenmpipython3.6.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESAFalsempiopenmpipython3.7.____cpython:
        CONFIG: linux_VTK_WITH_OSMESAFalsempiopenmpipython3.7.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESAFalsempiopenmpipython3.8.____cpython:
        CONFIG: linux_VTK_WITH_OSMESAFalsempiopenmpipython3.8.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESATruempimpichpython3.6.____cpython:
        CONFIG: linux_VTK_WITH_OSMESATruempimpichpython3.6.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESATruempimpichpython3.7.____cpython:
        CONFIG: linux_VTK_WITH_OSMESATruempimpichpython3.7.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESATruempimpichpython3.8.____cpython:
        CONFIG: linux_VTK_WITH_OSMESATruempimpichpython3.8.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESATruempinompipython3.6.____cpython:
        CONFIG: linux_VTK_WITH_OSMESATruempinompipython3.6.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESATruempinompipython3.7.____cpython:
        CONFIG: linux_VTK_WITH_OSMESATruempinompipython3.7.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESATruempinompipython3.8.____cpython:
        CONFIG: linux_VTK_WITH_OSMESATruempinompipython3.8.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESATruempiopenmpipython3.6.____cpython:
        CONFIG: linux_VTK_WITH_OSMESATruempiopenmpipython3.6.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESATruempiopenmpipython3.7.____cpython:
        CONFIG: linux_VTK_WITH_OSMESATruempiopenmpipython3.7.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_VTK_WITH_OSMESATruempiopenmpipython3.8.____cpython:
        CONFIG: linux_VTK_WITH_OSMESATruempiopenmpipython3.8.____cpython
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)